### ISSUE TITLE
Warnings.warn throwing error

### ISSUE THREAD

**Issue by javenell** [netnz2019/JamesADT2022#4]
D:/JamesADT2022/python/render.py:95: RuntimeWarning: Token outside board! Ignoring Turn
  raise warnings.warn("Token outside board! Ignoring Turn", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/JamesADT2022/python/render.py", line 95, in <module>
    raise warnings.warn("Token outside board! Ignoring Turn", RuntimeWarning)
TypeError: exceptions must derive from BaseException

**Comment by javenell** [comment]
solved by removing the raise in front of warnings.warn()...
